---
- name: Copy gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ rancid_home }}/.gitconfig"
    owner: rancid
    group: rancid
    mode: 0640
  tags: rancid

- name: List current git remotes
  command: >
    git remote
    chdir={{ rancid_home }}
  become_user: rancid
  register: current_git_remotes
  changed_when: false
  always_run: True
  tags:
    - rancid
    - rancid-remote

- name: Add host keys to known_hosts
  known_hosts:
    name: "{{ item.hostname }}"
    state: present
    key: "{{ item.host_key }}"
  become_user: rancid
  with_items: rancid_git_remotes
  tags:
    - rancid
    - known_hosts

- name: Add git remotes
  command: >
    git remote add {{ item.name }} {{ item.url }}
    chdir={{ rancid_home }}
  become_user: rancid
  with_items: rancid_git_remotes
  when: "item.name not in current_git_remotes.stdout_lines"
  tags:
    - rancid
    - rancid-remote

- name: Convert rancid_git_remotes.name into a list
  set_fact:
    git_remote_list: "{{ rancid_git_remotes | map(attribute = 'name') | list }}"
  tags:
    - rancid
    - rancid-remote

- name: Remove git remotes
  command: >
    git remote rm {{ item }}
    chdir={{ rancid_home }}
  become_user: rancid
  with_items: current_git_remotes.stdout_lines
  when: "item not in git_remote_list"
  tags:
    - rancid
    - rancid-remote

- name: Push to git remotes
  command: >
    git push {{ item.name }} master
    chdir={{ rancid_home }}
  register: push_status
  changed_when: "item.url in push_status.stderr"
  become_user: rancid
  with_items: rancid_git_remotes
  tags:
    - rancid
    - rancid-remote
