---
- name: Install dependencies for rancid-git
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - expect
    - git
    - perl-CGI
    - perl-LockFile-Simple
    - perl-MailTools
    - python-pip
    - diffstat
  tags:
    - rancid
    - yum

- name: Install Python packages
  easy_install:
    name: ansi2html
  tags:
    - rancid
    - yum

- name: Copy rancid-git rpm
  copy:
    src: rancid-git-{{ rancid_version }}.el6.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  tags:
    - rancid
    - updaterancid

- name: Install rancid-git
  yum:
    name: /tmp/rancid-git-{{ rancid_version }}.el6.x86_64.rpm
    state: present
  tags:
    - rancid
    - updaterancid
