---
- name: INSTALL | Copy rancid-git rpm
  copy:
    src: rancid-git-{{ rancid_version }}.el6.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  tags:
    - rancid
    - rancid-update

- name: INSTALL | Install rancid-git
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - /tmp/rancid-git-{{ rancid_version }}.el6.x86_64.rpm
    - python-pip
  tags:
    - rancid
    - rancid-update

- name: INSTALL | Install Python packages
  easy_install:
    name: ansi2html
  tags:
    - rancid
    - rancid-yum
