---
- name: Install deps for rancid-git
  yum: name={{ item }} state=present
  with_items:
    - expect
    - perl-cgi
  tags: [ 'rancid' , 'yum' ]

- name: Create rancid user account
  user: name=rancid
        comment="rancid"
        uid=557
        shell=/bin/bash
  tags: [ 'rancid' ]

- name: Get git-rancid source code
  git:  repo=git://github.com/dotwaffle/rancid-git
        dest=/home/rancid/rancid-git
        version={{ rancid_version }}
  tags: [ 'rancid' ]