---
- name: run rancid-cvs
  command: /usr/libexec/rancid/rancid-cvs
  become_user: rancid
  register: rancidcvs_run
  changed_when: rancidcvs_run.stdout != ''

- name: rehash aliases
  command: newaliases
